# Generated by Django 4.2.6 on 2023-10-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="data_nascimento",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="endereco",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="fb_link",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="genero",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_link",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telefone",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tiktok_link",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_link",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
